# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/gyx_uni/2_spring/cod/lab/lab5/lab5/lab5.srcs/sources_1/ip/MEM/MEM.xci
# IP: The module: 'MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gyx_uni/2_spring/cod/lab/lab5/lab5/lab5.srcs/sources_1/ip/MEM/MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/gyx_uni/2_spring/cod/lab/lab5/lab5/lab5.srcs/sources_1/ip/MEM/MEM.xci
# IP: The module: 'MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gyx_uni/2_spring/cod/lab/lab5/lab5/lab5.srcs/sources_1/ip/MEM/MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
