# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/gyx_uni/2_spring/cod/lab/lab4/lab4/lab4.srcs/sources_1/ip/VRAM/VRAM.xci
# IP: The module: 'VRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gyx_uni/2_spring/cod/lab/lab4/lab4/lab4.srcs/sources_1/ip/VRAM/VRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/gyx_uni/2_spring/cod/lab/lab4/lab4/lab4.srcs/sources_1/ip/VRAM/VRAM.xci
# IP: The module: 'VRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gyx_uni/2_spring/cod/lab/lab4/lab4/lab4.srcs/sources_1/ip/VRAM/VRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
