# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/gyx_uni/2_spring/cod/lab/lab6/lab6/.Xil/Vivado-5796-GyxPC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv D:/xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog {
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/.Xil/Vivado-5796-GyxPC/realtime/clk_wiz_0_stub.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/.Xil/Vivado-5796-GyxPC/realtime/MEM_stub.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/ALU.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Control_Unit.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Mux_2.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Mux_2_5bits.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Mux_4.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Reg_File.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Register.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/SignExtend_Unit.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/State_Machine.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/CPU.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/DDU.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/bcd_decoder.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/clock_500hz.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/clock_5hz.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/TOP.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Interrupt_Dst.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Interrupt_Ctrl.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Interrupt_flag.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Evaluate_Interrupt.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/clock_50khz.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/LED_Display.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/LED_Ctrl.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/LED_driver.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Score_Ctrl.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Score_Driver.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Data_Distributor.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Addr_Mux.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Input_Ctrl.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Input_Driver.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Input_Priority.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/IRQ_Handler.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Bluetooth_Priority.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Bluetooth_Driver.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/clock_9600hz.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Bluetooth_ReceiveData.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Bluetooth_TransmitData.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/B_Data_Decode.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/B_Data_Encode.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Ascii2Hex.v
      D:/gyx_uni/2_spring/cod/lab/lab6/lab6/lab6.srcs/sources_1/new/Hex2Ascii.v
    }
      rt::read_vhdl -lib xpm D:/xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top TOP
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/gyx_uni/2_spring/cod/lab/lab6/lab6/.Xil/Vivado-5796-GyxPC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
